<a href="https://colab.research.google.com/github/Hanniamtz/Actividad1/blob/main/Extracci%C3%B3n_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Hannia Nicole Martínez 
###A01552310

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df= pd.read_excel("Datos de Facturación.xlsx")
df

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

CVE_CLPV (valores: 1000 a 2000)

In [43]:
df['CVE_CLPV'] = pd.to_numeric(df['CVE_CLPV'], errors='coerce')
flt1 = df[(df['CVE_CLPV'] >= 1000) & (df['CVE_CLPV'] <= 2000)]
flt1

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.50,0.00,0
22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.50,0.00,0
65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaT,4135.00,0.00,0
71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.50,146.48,0
72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaT,976.50,146.48,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10821,F40237,1757.0,E,2.0,2023-02-24 15:18:17.570,2023-02-24,2023-02-13 00:00:00,2023-02-24,NaT,10088.40,0.00,0
10839,F40255,1583.0,E,2.0,2023-02-28 09:15:45.753,2023-02-28,2023-02-28 00:00:00,2023-03-30,NaT,3467.35,0.00,0
10845,F40261,1786.0,E,2.0,2023-02-28 11:15:32.527,2023-02-28,2023-03-03 00:00:00,2023-02-28,NaT,4663.80,0.00,0
10871,F40287,1453.0,E,1.0,2023-03-01 12:58:23.397,2023-03-01,2023-02-27 00:00:00,2023-03-31,NaT,9000.00,0.00,0
10876,F40292,1082.0,E,6.0,2023-03-02 11:00:54.770,2023-03-02,2023-03-01 00:00:00,2023-03-02,NaT,3262.00,0.00,0

In [44]:
flt1.to_csv("flt1.csv")
from google.colab import files 
files.download("flt1.csv")

CVE_VEND     (Todas las claves excepto “5” y “4”)

In [24]:
flt2=df[~(df["CVE_VEND"] == 5) & ~(df["CVE_VEND"] == 4)]
flt2

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

In [25]:
flt2.to_csv("flt2.csv")
from google.colab import files 
files.download("flt2.csv")

FECHA_ENT   (Fechas de “28/02/2022”)

In [32]:
flt3=df[df["FECHA_ENT"] == "2022-02-28 00:00:00"]
flt3

Empty DataFrame
Columns: [CVE_DOC, CVE_CLPV, STATUS, CVE_VEND, FECHAELAB, FECHA_DOC, FECHA_ENT, FECHA_VEN, FECHA_CANCELA, CAN_TOT, DES_TOT, DES_FIN]
Index: []

In [28]:
flt3.to_csv("flt3.csv")
from google.colab import files 
files.download("flt3.csv")

CAN_TOT       (Cantidades menores a 5951.7)   o  STATUS (“E”)

In [33]:
flt4=df[(df["CAN_TOT"] < 5951.7 ) | (df["STATUS"] == "E")]
flt4

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

In [34]:
flt4.to_csv("flt4.csv")
from google.colab import files 
files.download("flt4.csv")

Solo las columnas: CVE_DOC, FECHA_ENT, FECHA_VEN y CAN_TOT

In [10]:
flt5=df.iloc[ : ,[0,6,9]]
flt5

      CVE_DOC            FECHA_ENT  CAN_TOT
0      F29414  2019-09-03 00:00:00  3980.00
1      F29415  2019-09-03 00:00:00  1550.00
2      F29416  2019-09-03 00:00:00  1550.00
3      F29417  2019-09-03 00:00:00  1550.00
4      F29418  2019-09-03 00:00:00  2435.44
...       ...                  ...      ...
10890  F40306  2023-03-01 00:00:00  3272.00
10891  F40307  2023-03-06 00:00:00   504.15
10892  F40308  2023-03-06 00:00:00   275.68
10893  F40309  2023-03-07 00:00:00   129.30
10894  F40310  2023-03-01 00:00:00   517.20

[10895 rows x 3 columns]

In [35]:
flt5.to_csv("flt5.csv")
from google.colab import files 
files.download("flt5.csv")

Solo las filas de 7001-7099

In [9]:
flt6=df.iloc[ 7001:7100 , : ]   
flt6

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
7001,F36417,5271,E,3.0,2021-10-15 08:40:29.183,2021-10-15,2021-10-06 00:00:00,2021-11-14,NaT,8555.24,0.0,0
7002,F36418,5746,E,2.0,2021-10-15 08:51:03.463,2021-10-15,2021-10-14 00:00:00,2021-10-15,NaT,620.77,0.0,0
7003,F36419,2163,E,3.0,2021-10-15 08:56:23.280,2021-10-15,2021-10-15 00:00:00,2021-10-15,NaT,560.00,0.0,0
7004,F36420,1429,E,1.0,2021-10-15 09:01:08.393,2021-10-15,2021-10-15 00:00:00,2021-12-14,NaT,23625.00,0.0,0
7005,F36421,5039,E,1.0,2021-10-15 09:07:07.103,2021-10-15,2021-10-08 00:00:00,2022-01-13,NaT,3308.78,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
7095,F36511,4480,E,2.0,2021-10-27 13:07:43.223,2021-10-27,2021-10-27 00:00:00,2021-11-11,NaT,1137.50,0.0,0
7096,F36512,8186,E,2.0,2021-10-27 13:22:23.980,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaT,94.84,0.0,0
7097,F36513,4403,E,2.0,2021-10-27 13:35:40.677,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaT,847.00,0.0,0
7098,F36514,5589,E,2.0,2021-10-27 14:02:54.630,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaT,965.00,0.0,0
7099,F36515,5589,E,2.0,2021-10-27 14:04:26.797,2021-10-27,2021-10-26 00:00:00,2021-10-27,NaT,2106.00,0.0,0

In [38]:
flt6.to_csv("flt6.csv")
from google.colab import files 
files.download("flt6.csv")

-Index= CVE_VEND (valores: 1, 2)  (columna: FECHAELAB)

In [37]:
df1= pd.read_excel('Datos de Facturación.xlsx', index_col=3)
flt7=  df1.loc[[1,2], ["FECHAELAB"]]
flt7

                       FECHAELAB
CVE_VEND
1.0      2019-09-03 08:58:42.000
1.0      2019-09-03 09:55:14.000
1.0      2019-09-03 13:25:33.000
1.0      2019-09-03 13:33:23.000
1.0      2019-09-04 09:15:12.000
...                          ...
2.0      2023-03-06 16:09:39.013
2.0      2023-03-06 16:38:42.933
2.0      2023-03-06 17:02:33.390
2.0      2023-03-07 12:43:49.567
2.0      2023-03-07 12:45:58.407

[8665 rows x 1 columns]

In [39]:
flt7.to_csv("flt7.csv")
from google.colab import files 
files.download("flt7.csv")